<?php

namespace app\models;
use yii\base\Model;
use yii;
use yii\imagine\Image;
use yii\imagine\BaseImage;

class ImageUpload extends Model
{
    public $imageFile;

    public function rules()
    {
        return [
            ['imageFile', 'file', 'skipOnEmpty' => false, 'extensions' => 'jpg, png, jpeg']
        ];

        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return
            [
                'imageFile' => 'Fayl rasmi'
            ];
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public function upload($size){
        if ($this->validate()) {
            $path = Yii::getAlias('@uploads');
            $fileName = uniqid();
            $fileExt = $this->imageFile->extension;
            $fulName = $fileName . '.' . $fileExt;
            if ($this->imageFile->saveAs($path . '/' . $fulName)) {
                $thumb = $this->Imagine($fulName, $size);
                return [
                    'original' => $fulName,
                    'thumb' => $thumb
                ];
            }
            return false;
        }
    }




    public function Imagine($orginal_image,$size){
        $path = Yii::getAlias('@uploads');
        $thumbName= 'thumb_'.$orginal_image;
        if($size=='news') {
            Image::thumbnail($path . '/' . $orginal_image, 400, 250)->save($path . '/' . $thumbName);
        }
        else if($size=='pages'){
            Image::thumbnail($path . '/' . $orginal_image, 1000, 350)->save($path . '/' . $thumbName);
        }
        else if($size=='product'){
            Image::thumbnail($path . '/' . $orginal_image, 450, 300)->save($path . '/' . $thumbName);
        }
        else if($size=='gallery'){
            Image::thumbnail($path . '/' . $orginal_image, 450, 300)->save($path . '/' . $thumbName);
        }
        return $thumbName;
    }
}

?>
